version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    parallelism: 5
    steps:
      - checkout
      - run: |
            if [ "$CIRCLE_NODE_INDEX" == "2" ]; then
              circleci-agent step halt
            fi

